### ISSUE TITLE
Resolving ip forever

### ISSUE THREAD

**Issue by Marcin2654** [ORelio/Minecraft-Console-Client#1095]
When I start MCC i see:

```
Console Client for MC 1.4.6 to 1.15.2 - v1.15.2 - By ORelio & Contributors


Resolving e-craft.pl...

```
And nothing else.

EDIT:
When i connected to mc.e-craft.pl, after some time the message `Failed to connect to this IP.` appeared

**Comment by ORelio** [comment]
Unsure what is causing this, try with `debugmessages=true`, also what is your `resolvesrvrecords` setting?

**Comment by Marcin2654** [comment]
I tried to set `debugmessages=true` and now there are only more empty spaces. `resolvesrvrecords=fast`

**Comment by ORelio** [comment]
Will have a look at what could hang here.

**Comment by Marcin2654** [comment]
Did you find any solution?

**Comment by ORelio** [comment]
Hey, let me breath, I'm not working 24:7 on MCC 😅
So yes, I think it is fixed now, I'll let you check the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) to confirm this.

**Comment by Marcin2654** [comment]
Sorry for the pressure.
There is still the same problem. Nothing has changed.

**Comment by ORelio** [comment]
This is weird, now it should give up after 30 seconds by default, or 10 seconds in "fast" mode... 🤔

**Comment by Marcin2654** [comment]
The problem occurs on linux. On windows with the same settings everything works fine..
