### ISSUE TITLE
Entity command cause console froze

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1237]
Only occur in 1.12.2 and 1.13.2.
Like this:
![image](https://user-images.githubusercontent.com/39955851/91170413-6f870e80-e70b-11ea-8803-fbc4c468f18e.png)
![image](https://user-images.githubusercontent.com/39955851/91170619-bb39b800-e70b-11ea-8724-bfbf0dc454f8.png)

Also entity command output is a mess.
![image](https://user-images.githubusercontent.com/39955851/91170734-eae8c000-e70b-11ea-937a-b5552242ce64.png)

**Comment by ORelio** [comment]
Maybe rounding [Location.ToString()](https://github.com/ORelio/Minecraft-Console-Client/blob/70c991cd30d40d454e85435a674c743c3a520c60/MinecraftClient/Mapping/Location.cs#L300) to hide decimals would make it more readable.

**Comment by Nekiplay** [comment]
> Only occur in 1.12.2 and 1.13.2.
> Like this:
> ![image](https://user-images.githubusercontent.com/39955851/91170413-6f870e80-e70b-11ea-8803-fbc4c468f18e.png)
> ![image](https://user-images.githubusercontent.com/39955851/91170619-bb39b800-e70b-11ea-8724-bfbf0dc454f8.png)
> 
> Also entity command output is a mess.
> ![image](https://user-images.githubusercontent.com/39955851/91170734-eae8c000-e70b-11ea-937a-b5552242ce64.png)
This should have been fixed #1238

**Comment by ReinforceZwei** [comment]
It is not fixed.
![image](https://user-images.githubusercontent.com/39955851/91379590-9fdac400-e855-11ea-919b-bf3dffcbc3c6.png)

**Comment by Nekiplay** [comment]
Item.Type Equals null
![image](https://user-images.githubusercontent.com/35975332/91380687-056f8600-e83f-11ea-9766-5d28374fabd4.png)

**Comment by ReinforceZwei** [comment]
I think you need to fix this method. Those metadata key could be different between version.
![image](https://user-images.githubusercontent.com/39955851/91381015-f0075580-e858-11ea-9705-940680452c94.png)

**Comment by Nekiplay** [comment]
I tried to do this, but it seriously gives an error that Item is null
![image](https://user-images.githubusercontent.com/35975332/91381343-9eeb6780-e840-11ea-9b66-6c186ac5e92a.png)

**Comment by Nekiplay** [comment]
Fixed in #1241
