### ISSUE TITLE
Can't run "mono MinecraftClient.exe"

### ISSUE THREAD

**Issue by TheColorhack** [ORelio/Minecraft-Console-Client#481]
When I try to run the
```
mono MinecraftClient.exe
```
It just returns
>Cannot open assembly 'MinecraftClient.exe' : No such file or directory.

I'm in no way good at coding but I think the 'mono' command is looking for an .exe file in the config folder?
I'm using Ubuntu terminal only and I really want this to work. Please help!

**Comment by Icy-Zach** [comment]
open a terminal and type "sudo apt-get install mono-runtime" and install that
then open the folder that the console client is in press f4 and type "mono MinecraftClient.exe" case sensitive

**Comment by TheColorhack** [comment]
After doing the "apt-get" command I got something about the library still being installed. Then I went through every folder I have and did "mono MinecraftClient.exe" And got the same message. "Cannot open assembly 'MinecraftClient.exe' : No such file or directory."
The "mono" command is looking for a file named "MinecraftClient.exe" but that file doesn't exist anywhere in the program.

**Comment by Icy-Zach** [comment]
how about "sudo apt-get update"?

**Comment by ORelio** [comment]
Thanks @Icy-Zach for taking some to answer issues, I just can't cope with all of them so this is higly appreciated.
@Thecolorhack
You are likely typing your command from the wrong folder, try "pwd" to see where you are, "cd /path/to/my/dir" to move to the correct dir and "ls" to list files in the current directory.

**Comment by LQ1234** [comment]
download exe from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts?
then mono that

**Comment by TheColorhack** [comment]
Ok sorry I'm just an idiot. I forgot to download the Minecraft client.exe. Sorry for wasting everyone's time :(. It works amazing now!

**Comment by ORelio** [comment]
At least the problem is solved and I must admit I laughed a bit so my time wasn't fully wasted :p

**Comment by Icy-Zach** [comment]
a good morning laugh =D glad to hear your all up and running

**Comment by Jumpyy123** [comment]
@ORelio I'm having a similar problem, I've got MinecraftClient installed, on my Desktop and im trying to run it on a VPS, but I've installed a lot of "Mono" stuff and all that, but I still can't seem to get it working, can you please help?

**Comment by ORelio** [comment]
Since the issue seems resolved, I'll close the thread. (@Jumpyy123 : continuing in #595 )
