### ISSUE TITLE
Alerts on server cause spam

### ISSUE THREAD

**Issue by dagonzaros** [ORelio/Minecraft-Console-Client#95]
When connected to the hub of our server, I'm getting spammed by the "alert" messages we display. In-game they appear right above the XP bar, but in the client they spam as if chat was being flooded.
![image](https://cloud.githubusercontent.com/assets/1350574/10146616/160fe4da-65e7-11e5-80b6-53c30ed03fba.png)

**Comment by ORelio** [comment]
Ah, yes, text over the upper-screen XP bar appears in chat - as MCC does not have a XP bar - but seems like a setting for disabling them would be useful here.

**Comment by ORelio** [comment]
You can now disable these messages by changing a setting in the configuration file:
````INI
showxpbarmessages=false
````
This change is available in [this development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/50) so that you can test it without having to wait.

**Comment by dagonzaros** [comment]
Hey I downloaded that file, the configuration option doesn't appear in the new MinecraftClient.ini and now I'm unable to chat once connected to a server, but the server does register me as connected. I can't receive or send chat.

**Comment by ORelio** [comment]
A configuration file should be generated on first launch, with default settings, then the line
````INI
showxpbarmessages=false
````
should be found in the
````INI
#Advanced settings
````
section. (This default file is [hardcoded](https://github.com/ORelio/Minecraft-Console-Client/blob/8bd130eb3a9edeeec84bd55ddc1fae4d9be6b215/MinecraftClient/Settings.cs#L403)).
Please double check you downloaded the [latest development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/history) ...?
Are you getting any error message, or something?

**Comment by dagonzaros** [comment]
I did download the latest development build, however, it doesn't let me send/receive chat, it doesn't disconnect me either. I am not even getting the spam of alert messages that I was before, without the setting changed.

**Comment by ORelio** [comment]
Would you mind if I directly try on your server? This would help because on my test server I can send and receive messages properly without issue.

**Comment by dagonzaros** [comment]
play.islandclash.com I'll be logged in via the normal client, please mention _Dagon in chat

**Comment by ORelio** [comment]
Okay, found the issue, it was linked to recent changes regarding brand information (856075394967bc626642c39cf7c5a5ac1ebf20a9) and that is now fixed (b25a665c82fa035e1fe240af784ab8ba577af7b3). This was totally unrelated to message filters and apparently happened due to a race condition. A packet was sent when joining game, but the server may still be in "login" mode so invalid packet and silent disconnect. Tested with `showxpbarmessages=false` on your server, spam is filtered as expected now :)

**Comment by dagonzaros** [comment]
Hey as shown here, I'm still not getting the spam filtered.

http://puu.sh/ktMBf/c5cce06130.png

**Comment by ORelio** [comment]
My bad. Fixed :fearful:

**Comment by dagonzaros** [comment]
Ty
